version: '3'
services: 
  ##################
  ## Service One ###
  ##################
  serviceoneapp:
    build: 
      context: .
      dockerfile: ServiceOne/ServiceOne/Dockerfile
    ports: 
      - "50001:50001"
      - "3500:3500"
    depends_on: 
      - redis
      - placement
    networks: 
      - dapr-pubsub-shared
  serviceoneapp-dapr:
    image: "daprio/daprd:edge"
    command: [ "./daprd",
    "-app-id", "serviceoneapp",
    "-app-port", "8094",
    "-placement-host-address", "placement:50007",
    "-dapr-grpc-port", "50001",
    "-components-path", "/ComponentsLocal"]
    volumes: 
      - "./ComponentsLocal/:/ComponentsLocal"
    depends_on: 
      - serviceoneapp
    network_mode: "service:serviceoneapp"
  ###############
  ## ServiceTwo##
  ###############
  servicetwoapp:
    build: 
      context: .
      dockerfile: ServiceTwo/ServiceTwo/Dockerfile
    ports: 
      - "50002:50002"
    depends_on: 
      - redis
      - placement
    networks: 
      - dapr-pubsub-shared
  servicetwoapp-dapr:
    image: "daprio/daprd:edge"
    command: [ "./daprd",
    "-app-id", "servicetwoapp",
    "-app-port", "8095",
    "-placement-host-address", "placement:50007",
    "-dapr-grpc-port", "50001",
    "-components-path", "/ComponentsLocal"]
    volumes: 
      - "./ComponentsLocal/:/ComponentsLocal"
    depends_on: 
      - servicetwoapp
    network_mode: "service:servicetwoapp"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50007"]
    ports:
      - "50007:50007"
    networks:
      - dapr-pubsub-shared
  ###############
  #### Redis ####
  ###############
  redis:
    image: "redis:alpine"
    ports: 
      - "6380:6379"
    networks: 
      - dapr-pubsub-shared
networks: 
  dapr-pubsub-shared: